version: '3'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '3050:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ui:/var/www/html
  php:
    image: php:7.3-fpm
    volumes:
      - ./php:/var/www/html
    ports:
      - '9000:9000'
